= XYZ Reader 

XYZ Reader: A mock RSS feed reader featuring banner photos and headlines. Download the code here.
The app is currently functional, and work in most cases for most users.

Your job will be to take the user feedback in the UI Review node, and implement changes that will improve the UI and make it conform to Material Design.

Supporting Courses
You should have the skills you need to complete this app after completing:

Developing Android Apps
Advanced Android App Development
Material Design for Android Developers
You can also refer to the Material Design specification.

Required Tasks
Download a zip file of the app.
Read the UI Review in the next node.
Spend time exploring the current state of the app, looking for ways it could be improved. The app will need multiple improvements. Be sure to look specifically at issues called out in the UI Review.
Execute the improvements!
Make a single GitHub repo with your code for the app and submit it through the Nanodegree portal. See the Submission and Evaluation node for detailed instructions.

## Libraries

* [Glide](https://github.com/bumptech/glide)
* [OkHttp](https://github.com/square/okhttp)
* [Butter Knife](https://jakewharton.github.io/butterknife/)
* [Android-Iconics](https://github.com/mikepenz/Android-Iconics)
* [Volley](https://github.com/google/volley)

## License

    Copyright 2018 Benedetto Pellerito

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

